## ================================================================
## True DAPC for PPG Xtar reduced ingroup datasets
##
## Inputs:
##   VCFs generated by filter_Xtar_ingroup_MAF05.R
##
## Workflow:
##   - Outgroups were removed before the MAF 0.05 filter.
##   - Treats RADseq genotypes as haploid.
##   - Uses a reproducible random subset of up to 10,000 loci,
##     matching the computational scale of the previous analysis.
##   - Selects the number of retained PCs using adegenet::xvalDapc().
##   - Runs adegenet::dapc() using current species determinations
##     as predefined groups.
##   - Runs MIN4, MIN27, and MIN53 independently.
##
## Interpretation:
##   This is a supervised classification analysis relative to
##   current species determinations, not an independent clustering
##   or species-delimitation analysis.
## ================================================================

suppressPackageStartupMessages({
  library(vcfR)
  library(adegenet)
  library(tidyverse)
  library(parallel)
})

## ----------------------------------------------------------
## 0. Paths and settings
## ----------------------------------------------------------

base_dir <- Sys.getenv("PPG_DATA_DIR")

if (base_dir == "") {
  stop("Set PPG_DATA_DIR to the directory containing the PPG analysis files.")
}
meta_path <- file.path(base_dir, "PPG_metadata.csv")

vcf_dir <- file.path(
  base_dir,
  "VCF_Xtar_reduced_ingroup_MAF05"
)

## New folder preserves previous PCA+LDA outputs.
out_base <- file.path(
  base_dir,
  "DAPC_Xtar_reduced_ingroup_MAF05"
)
dir.create(out_base, showWarnings = FALSE, recursive = TRUE)

assemblies <- tibble::tribble(
  ~asm, ~vcf_path,
  "MIN4_Xtar_reduced",
  file.path(
    vcf_dir,
    "MIN4_Xtar_reduced_ingroup_maf05.recode.vcf"
  ),
  "MIN27_Xtar_reduced",
  file.path(
    vcf_dir,
    "MIN27_Xtar_reduced_ingroup_maf05.recode.vcf"
  ),
  "MIN53_Xtar_reduced",
  file.path(
    vcf_dir,
    "MIN53_Xtar_reduced_ingroup_maf05.recode.vcf"
  )
)

outgroup_samples <- c(
  "TW4688_P_cristiferum_Madagascar",
  "TW5198_P_reticulatum_USA_IL"
)

## Keep the same computational scale as the previous analysis.
max_loci_for_dapc <- 10000
locus_subset_seed <- 999

## Candidate PC values for cross-validation.
## With only three P. louisianae samples, xvalDapc automatically
## reduces the training proportion so every group is represented
## in both training and validation sets.
xval_pc_grid <- seq(5, 50, by = 5)
xval_reps <- 100

## Linux server: use a modest number of cores.
n_cores <- min(4L, max(1L, parallel::detectCores() - 1L))

## Six predefined species groups permit at most five DA axes.
n_da <- 5

## ----------------------------------------------------------
## 1. Species order, colors, and shapes
## ----------------------------------------------------------

species_full_levels <- c(
  "P.perforatum",
  "P.hypotropum",
  "P.subrigidum",
  "P.louisianae",
  "P.preperforatum",
  "P.hypoleucinum"
)

species_cols_hex <- c(
  "P.perforatum"    = "#006400",
  "P.hypotropum"    = "#90EE90",
  "P.subrigidum"    = "#8B0000",
  "P.louisianae"    = "#F08080",
  "P.preperforatum" = "#4B0082",
  "P.hypoleucinum"  = "#D8BFD8"
)

species_shapes <- c(
  "P.perforatum"    = 15,
  "P.hypotropum"    = 16,
  "P.subrigidum"    = 15,
  "P.louisianae"    = 16,
  "P.preperforatum" = 15,
  "P.hypoleucinum"  = 16
)

species_labels <- c(
  "P.perforatum"    = "italic(P.~perforatum)",
  "P.hypotropum"    = "italic(P.~hypotropum)",
  "P.subrigidum"    = "italic(P.~subrigidum)",
  "P.louisianae"    = "italic(P.~louisianae)",
  "P.preperforatum" = "italic(P.~preperforatum)",
  "P.hypoleucinum"  = "italic(P.~hypoleucinum)"
)

focal_species <- c(
  "perforatum",
  "hypotropum",
  "subrigidum",
  "louisianae",
  "preperforatum",
  "hypoleucinum"
)

## ----------------------------------------------------------
## 2. Logging
## ----------------------------------------------------------

log_file <- file.path(
  out_base,
  "DAPC_Xtar_reduced_ingroup_MAF05_log.txt"
)

if (file.exists(log_file)) {
  file.remove(log_file)
}

log_msg <- function(...) {
  ts <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  line <- paste0(ts, " - ", paste(..., collapse = ""))
  cat(line, "\n", file = log_file, append = TRUE)
  message(paste(..., collapse = ""))
}

log_msg("=== Starting true DAPC pipeline ===")
log_msg("Maximum loci per dataset: ", max_loci_for_dapc)
log_msg("Locus subset seed: ", locus_subset_seed)
log_msg(
  "Cross-validation PC grid: ",
  paste(xval_pc_grid, collapse = ", ")
)
log_msg("Cross-validation replicates per PC value: ", xval_reps)
log_msg("Parallel cores: ", n_cores)

## ----------------------------------------------------------
## 3. Metadata helpers
## ----------------------------------------------------------

as_logical_outgroup <- function(x) {
  if (is.logical(x)) return(x)
  x_chr <- tolower(trimws(as.character(x)))
  x_chr %in% c("true", "t", "1", "yes", "y")
}

standardize_species <- function(x) {
  x <- tolower(trimws(as.character(x)))
  x <- gsub("^p\\.", "", x)
  x <- gsub("^p_", "", x)
  x
}

species_to_full <- function(sp) {
  paste0("P.", standardize_species(sp))
}

ensure_probability_columns <- function(df, wanted_cols) {
  missing_cols <- setdiff(wanted_cols, colnames(df))

  if (length(missing_cols) > 0) {
    for (m in missing_cols) {
      df[[m]] <- 0
    }
  }

  df[, wanted_cols, drop = FALSE]
}

## ----------------------------------------------------------
## 4. Load metadata
## ----------------------------------------------------------

if (!file.exists(meta_path)) {
  stop("Metadata file not found: ", meta_path)
}

meta_raw <- readr::read_csv(
  meta_path,
  show_col_types = FALSE
)

required_cols <- c("sample", "species")
missing_required <- setdiff(
  required_cols,
  colnames(meta_raw)
)

if (length(missing_required) > 0) {
  stop(
    "Metadata is missing required columns: ",
    paste(missing_required, collapse = ", ")
  )
}

meta <- meta_raw %>%
  mutate(
    sample = trimws(as.character(sample)),
    species = standardize_species(species),
    is_outgroup = if (
      "is_outgroup" %in% colnames(.)
    ) {
      as_logical_outgroup(is_outgroup)
    } else {
      FALSE
    },
    is_outgroup = is_outgroup |
      sample %in% outgroup_samples,
    species_full = factor(
      species_to_full(species),
      levels = species_full_levels
    )
  )

meta_focal <- meta %>%
  filter(
    species %in% focal_species,
    !is_outgroup
  )

log_msg("Metadata rows total: ", nrow(meta))
log_msg(
  "Metadata rows focal ingroup: ",
  nrow(meta_focal)
)

## ----------------------------------------------------------
## 5. Main DAPC function
## ----------------------------------------------------------

run_dapc_for_assembly <- function(
  asm,
  vcf_path,
  meta,
  out_dir_base
) {

  log_msg("\n========================================")
  log_msg("Assembly: ", asm)
  log_msg("VCF: ", vcf_path)
  log_msg("========================================")

  if (!file.exists(vcf_path)) {
    stop("VCF not found: ", vcf_path)
  }

  out_dir <- file.path(
    out_dir_base,
    paste0("DAPC_", asm)
  )
  dir.create(
    out_dir,
    showWarnings = FALSE,
    recursive = TRUE
  )

  ## ------------------------------------------------------
  ## 5a. Read and validate ingroup-filtered VCF
  ## ------------------------------------------------------

  vcf <- read.vcfR(
    vcf_path,
    verbose = FALSE
  )

  sample_names <- colnames(vcf@gt)[-1]
  n_variant_records <- nrow(vcf@fix)

  log_msg(
    "Variant records in filtered VCF: ",
    n_variant_records
  )
  log_msg(
    "Individuals in filtered VCF: ",
    length(sample_names)
  )

  remaining_outgroups <- intersect(
    sample_names,
    outgroup_samples
  )

  if (length(remaining_outgroups) > 0) {
    stop(
      "Outgroups remain in VCF: ",
      paste(remaining_outgroups, collapse = ", ")
    )
  }

  if (length(sample_names) != 104) {
    stop(
      "Expected 104 ingroup samples, found ",
      length(sample_names),
      " for ",
      asm
    )
  }

  ## ------------------------------------------------------
  ## 5b. Convert to genlight and match metadata
  ## ------------------------------------------------------

  gl <- vcfR2genlight(vcf)
  ploidy(gl) <- rep(1L, nInd(gl))
  indNames(gl) <- trimws(indNames(gl))

  missing_metadata <- setdiff(
    indNames(gl),
    meta$sample
  )

  if (length(missing_metadata) > 0) {
    stop(
      "Samples in VCF but missing from metadata: ",
      paste(missing_metadata, collapse = ", ")
    )
  }

  keep_samples <- intersect(
    indNames(gl),
    meta$sample
  )

  gl <- gl[
    match(keep_samples, indNames(gl)),
  ]

  meta_sub <- meta %>%
    filter(sample %in% keep_samples) %>%
    arrange(match(sample, keep_samples)) %>%
    mutate(
      species_full = factor(
        species_to_full(species),
        levels = species_full_levels
      )
    )

  if (!all(indNames(gl) == meta_sub$sample)) {
    stop(
      "Sample order mismatch between genlight and metadata for ",
      asm
    )
  }

  if (nInd(gl) != 104) {
    stop(
      "Expected 104 matched ingroup samples, found ",
      nInd(gl),
      " for ",
      asm
    )
  }

  grp <- droplevels(meta_sub$species_full)

  log_msg("Individuals used: ", nInd(gl))
  log_msg("Loci in genlight: ", nLoc(gl))
  log_msg(
    "Species counts: ",
    paste(
      capture.output(print(table(grp))),
      collapse = " | "
    )
  )

  ## ------------------------------------------------------
  ## 5c. Mean imputation and locus cleaning
  ## ------------------------------------------------------

  X <- tab(
    gl,
    NA.method = "mean",
    freq = FALSE
  )
  X <- as.matrix(X)

  finite_ok <- apply(
    X,
    2,
    function(z) all(is.finite(z))
  )

  var_ok <- apply(
    X,
    2,
    function(z) {
      if (!all(is.finite(z))) return(FALSE)
      var(z) > 0
    }
  )

  keep_cols <- finite_ok & var_ok

  n_nonfinite <- sum(!finite_ok)
  n_zero_variance <- sum(finite_ok & !var_ok)

  X <- X[, keep_cols, drop = FALSE]

  log_msg(
    "Loci removed as non-finite: ",
    n_nonfinite
  )
  log_msg(
    "Loci removed as zero variance: ",
    n_zero_variance
  )
  log_msg(
    "Cleaned loci before thinning: ",
    ncol(X)
  )

  ## ------------------------------------------------------
  ## 5d. Reproducible locus subset
  ## ------------------------------------------------------

  if (
    is.finite(max_loci_for_dapc) &&
    ncol(X) > max_loci_for_dapc
  ) {
    set.seed(locus_subset_seed)

    selected_loci <- sample(
      seq_len(ncol(X)),
      max_loci_for_dapc,
      replace = FALSE
    )

    X_dapc <- X[
      ,
      selected_loci,
      drop = FALSE
    ]

    selected_locus_names <- colnames(X)[selected_loci]

    log_msg(
      "Randomly retained ",
      ncol(X_dapc),
      " loci for DAPC"
    )
  } else {
    X_dapc <- X
    selected_locus_names <- colnames(X)

    log_msg(
      "Using all ",
      ncol(X_dapc),
      " cleaned loci for DAPC"
    )
  }

  readr::write_csv(
    tibble(
      locus = selected_locus_names
    ),
    file.path(
      out_dir,
      paste0(asm, "_DAPC_selected_loci.csv")
    )
  )

  ## ------------------------------------------------------
  ## 5e. Cross-validation of retained PC number
  ## ------------------------------------------------------

  ## Remove candidate values that cannot be retained given
  ## sample size and group structure.
  pc_grid_use <- xval_pc_grid[
    xval_pc_grid < (nrow(X_dapc) - nlevels(grp))
  ]

  if (length(pc_grid_use) == 0) {
    stop(
      "No valid PC values remain for cross-validation in ",
      asm
    )
  }

  log_msg(
    "Running xvalDapc with PC values: ",
    paste(pc_grid_use, collapse = ", ")
  )

  set.seed(20260716)

  xval_time <- system.time({
    xval <- xvalDapc(
      X_dapc,
      grp = grp,
      n.pca.max = max(pc_grid_use),
      n.da = n_da,
      result = "groupMean",
      center = TRUE,
      scale = FALSE,
      n.pca = pc_grid_use,
      n.rep = xval_reps,
      xval.plot = FALSE,
      parallel = "multicore",
      ncpus = n_cores
    )
  })

  log_msg(
    "xvalDapc elapsed time (sec): ",
    round(xval_time[["elapsed"]], 1)
  )

  ## adegenet documents these seven list elements in order.
  xval_results <- xval[[1]]
  random_chance <- xval[[2]]
  mean_success <- xval[[3]]
  best_mean_success_pc <- xval[[4]]
  rmse <- xval[[5]]
  best_mse_pc <- as.integer(xval[[6]])

  log_msg(
    "PCs with highest mean assignment success: ",
    best_mean_success_pc
  )
  log_msg(
    "PCs with lowest RMSE: ",
    best_mse_pc
  )

  ## Save cross-validation replicate results.
  readr::write_csv(
    as.data.frame(xval_results),
    file.path(
      out_dir,
      paste0(asm, "_DAPC_cross_validation_replicates.csv")
    )
  )

  xval_summary <- tibble(
    n_pca = as.integer(names(mean_success)),
    mean_assignment_success = as.numeric(mean_success),
    rmse = as.numeric(rmse)
  )

  readr::write_csv(
    xval_summary,
    file.path(
      out_dir,
      paste0(asm, "_DAPC_cross_validation_summary.csv")
    )
  )

  readr::write_csv(
    tibble(
      statistic = c(
        "random_chance_lower",
        "random_chance_median",
        "random_chance_upper",
        "best_mean_success_pc",
        "best_mse_pc"
      ),
      value = c(
        as.numeric(random_chance),
        as.numeric(best_mean_success_pc),
        as.numeric(best_mse_pc)
      )
    ),
    file.path(
      out_dir,
      paste0(asm, "_DAPC_cross_validation_key_values.csv")
    )
  )

  ## Cross-validation plot.
  xval_plot <- ggplot(
    as.data.frame(xval_results),
    aes(
      x = factor(n.pca),
      y = success
    )
  ) +
    geom_boxplot(
      outlier.shape = NA,
      linewidth = 0.45
    ) +
    geom_jitter(
      width = 0.16,
      alpha = 0.25,
      size = 0.8
    ) +
    geom_vline(
      xintercept = which(
        sort(unique(xval_results$n.pca)) ==
          best_mse_pc
      ),
      linetype = "dashed",
      linewidth = 0.6
    ) +
    coord_cartesian(ylim = c(0, 1)) +
    theme_bw() +
    labs(
      x = "Number of retained principal components",
      y = "Mean group assignment success",
      title = paste(
        "DAPC cross-validation -",
        asm
      )
    ) +
    theme(
      plot.title = element_text(hjust = 0.5)
    )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_cross_validation.pdf")
    ),
    xval_plot,
    width = 7,
    height = 5
  )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_cross_validation.png")
    ),
    xval_plot,
    width = 7,
    height = 5,
    dpi = 300
  )

  ## ------------------------------------------------------
  ## 5f. Final adegenet DAPC
  ## ------------------------------------------------------

  dapc_obj <- dapc(
    X_dapc,
    grp = grp,
    n.pca = best_mse_pc,
    n.da = n_da,
    center = TRUE,
    scale = FALSE,
    var.contrib = FALSE,
    var.loadings = FALSE,
    pca.info = TRUE
  )

  log_msg(
    "Final DAPC retained PCs: ",
    dapc_obj$n.pca
  )
  log_msg(
    "Final DAPC retained DA axes: ",
    dapc_obj$n.da
  )

  ## ------------------------------------------------------
  ## 5g. Scores, posterior probabilities, and assignment
  ## ------------------------------------------------------

  coords <- as.data.frame(
    dapc_obj$ind.coord
  )

  if (ncol(coords) == 1) {
    coords$LD2 <- 0
  }

  colnames(coords)[1:2] <- c(
    "LD1",
    "LD2"
  )

  coords$sample <- meta_sub$sample
  coords$species_full <- grp
  coords$predicted_group <- dapc_obj$assign

  posterior <- as.data.frame(
    dapc_obj$posterior
  )

  posterior <- ensure_probability_columns(
    posterior,
    species_full_levels
  )

  posterior$sample <- meta_sub$sample
  posterior$species_full <- grp
  posterior$predicted_group <- dapc_obj$assign

  assignment_table <- tibble(
    sample = meta_sub$sample,
    current_species = grp,
    predicted_species = dapc_obj$assign,
    correctly_classified =
      grp == dapc_obj$assign
  )

  confusion <- as.data.frame.matrix(
    table(
      Current = grp,
      Predicted = dapc_obj$assign
    )
  ) %>%
    rownames_to_column("current_species")

  readr::write_csv(
    coords,
    file.path(
      out_dir,
      paste0(asm, "_DAPC_scores.csv")
    )
  )

  readr::write_csv(
    posterior,
    file.path(
      out_dir,
      paste0(asm, "_DAPC_posterior_probabilities.csv")
    )
  )

  readr::write_csv(
    assignment_table,
    file.path(
      out_dir,
      paste0(asm, "_DAPC_assignments.csv")
    )
  )

  readr::write_csv(
    confusion,
    file.path(
      out_dir,
      paste0(asm, "_DAPC_confusion_matrix.csv")
    )
  )

  ## ------------------------------------------------------
  ## 5h. LD1-LD2 scatterplot
  ## ------------------------------------------------------

  scatter_plot <- ggplot(
    coords,
    aes(
      x = LD1,
      y = LD2,
      color = species_full,
      shape = species_full
    )
  ) +
    geom_point(
      size = 2.6,
      alpha = 0.95
    ) +
    scale_color_manual(
      values = species_cols_hex,
      breaks = species_full_levels,
      labels = parse(text = species_labels),
      drop = FALSE,
      name = "Species"
    ) +
    scale_shape_manual(
      values = species_shapes,
      breaks = species_full_levels,
      labels = parse(text = species_labels),
      drop = FALSE,
      name = "Species"
    ) +
    theme_bw() +
    labs(
      x = "LD1",
      y = "LD2",
      title = paste(
        "DAPC -",
        asm
      )
    ) +
    theme(
      legend.position = "right",
      plot.title = element_text(hjust = 0.5)
    )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_scatter.pdf")
    ),
    scatter_plot,
    width = 7,
    height = 6
  )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_scatter.png")
    ),
    scatter_plot,
    width = 7,
    height = 6,
    dpi = 300
  )

  ## ------------------------------------------------------
  ## 5i. Posterior membership barplot
  ## ------------------------------------------------------

  sample_order <- posterior %>%
    arrange(
      species_full,
      sample
    ) %>%
    pull(sample)

  posterior_long <- posterior %>%
    select(
      sample,
      species_full,
      all_of(species_full_levels)
    ) %>%
    pivot_longer(
      cols = all_of(species_full_levels),
      names_to = "posterior_group",
      values_to = "probability"
    ) %>%
    mutate(
      sample = factor(
        sample,
        levels = sample_order
      ),
      posterior_group = factor(
        posterior_group,
        levels = species_full_levels
      )
    )

  membership_plot <- ggplot(
    posterior_long,
    aes(
      x = sample,
      y = probability,
      fill = posterior_group
    )
  ) +
    geom_col(width = 0.92) +
    scale_fill_manual(
      values = species_cols_hex,
      breaks = species_full_levels,
      labels = parse(text = species_labels),
      drop = FALSE,
      name = "Posterior group"
    ) +
    theme_bw() +
    labs(
      x = NULL,
      y = "Posterior membership probability",
      title = paste(
        "DAPC posterior membership -",
        asm
      )
    ) +
    theme(
      axis.text.x = element_text(
        angle = 90,
        hjust = 1,
        vjust = 0.5,
        size = 4
      ),
      legend.position = "right",
      plot.title = element_text(hjust = 0.5)
    )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_membership.pdf")
    ),
    membership_plot,
    width = 20,
    height = 6
  )

  ggsave(
    file.path(
      out_dir,
      paste0(asm, "_DAPC_membership.png")
    ),
    membership_plot,
    width = 20,
    height = 6,
    dpi = 300
  )

  ## ------------------------------------------------------
  ## 5j. Save metadata and R objects
  ## ------------------------------------------------------

  readr::write_csv(
    meta_sub,
    file.path(
      out_dir,
      paste0(asm, "_metadata_used.csv")
    )
  )

  saveRDS(
    list(
      assembly = asm,
      vcf_path = vcf_path,
      metadata = meta_sub,
      cleaned_matrix_dimensions = dim(X),
      dapc_matrix_dimensions = dim(X_dapc),
      selected_loci = selected_locus_names,
      cross_validation = xval,
      best_mse_pc = best_mse_pc,
      dapc = dapc_obj,
      scores = coords,
      posterior = posterior,
      assignments = assignment_table,
      confusion_matrix = confusion,
      scatter_plot = scatter_plot,
      membership_plot = membership_plot,
      xval_plot = xval_plot
    ),
    file = file.path(
      out_dir,
      paste0(asm, "_DAPC_objects.rds")
    )
  )

  log_msg("Finished assembly: ", asm)

  invisible(
    list(
      assembly = asm,
      best_mse_pc = best_mse_pc,
      xval = xval,
      dapc = dapc_obj,
      scores = coords,
      posterior = posterior,
      assignments = assignment_table,
      confusion = confusion
    )
  )
}

## ----------------------------------------------------------
## 6. Run all assemblies
## ----------------------------------------------------------

results <- list()

for (i in seq_len(nrow(assemblies))) {
  results[[assemblies$asm[i]]] <-
    run_dapc_for_assembly(
      asm = assemblies$asm[i],
      vcf_path = assemblies$vcf_path[i],
      meta = meta_focal,
      out_dir_base = out_base
    )
}

saveRDS(
  results,
  file.path(
    out_base,
    "DAPC_Xtar_reduced_ingroup_MAF05_all_results.rds"
  )
)

log_msg("=== Finished true DAPC pipeline ===")
