## ================================================================
## PCA for PPG Xtar reduced ingroup datasets
##
## Inputs are VCFs generated by filter_Xtar_ingroup_MAF05.R.
## Outgroups were removed before applying MAF 0.05.
## Uses all cleaned loci and treats RADseq genotypes as haploid.
## Produces PC1-PC2, PC1-PC3, PC2-PC3, and PC3-PC4 plots.
## ================================================================

suppressPackageStartupMessages({
  library(vcfR)
  library(adegenet)
  library(ggplot2)
  library(dplyr)
})

## ----------------------------------------------------------
## 0. Paths and settings
## ----------------------------------------------------------

base_dir <- Sys.getenv("PPG_DATA_DIR")

if (base_dir == "") {
  stop("Set PPG_DATA_DIR to the directory containing the PPG analysis files.")
}
meta_path <- file.path(base_dir, "PPG_metadata.csv")
vcf_dir <- file.path(base_dir, "VCF_Xtar_reduced_ingroup_MAF05")

## New folder preserves the earlier PCA outputs.
out_base <- file.path(base_dir, "PCA_Xtar_reduced_ingroup_MAF05_all_loci")
dir.create(out_base, showWarnings = FALSE, recursive = TRUE)

vcf_paths <- list(
  MIN4_Xtar_reduced = file.path(vcf_dir, "MIN4_Xtar_reduced_ingroup_maf05.recode.vcf"),
  MIN27_Xtar_reduced = file.path(vcf_dir, "MIN27_Xtar_reduced_ingroup_maf05.recode.vcf"),
  MIN53_Xtar_reduced = file.path(vcf_dir, "MIN53_Xtar_reduced_ingroup_maf05.recode.vcf")
)

outgroup_samples <- c(
  "TW4688_P_cristiferum_Madagascar",
  "TW5198_P_reticulatum_USA_IL"
)

focal_species <- c(
  "perforatum", "hypotropum", "subrigidum",
  "louisianae", "preperforatum", "hypoleucinum"
)

pc_pairs <- list(
  c("PC1", "PC2"),
  c("PC1", "PC3"),
  c("PC2", "PC3"),
  c("PC1", "PC4"),
  c("PC2", "PC4"),
  c("PC3", "PC4")
)

## ----------------------------------------------------------
## 1. Logging
## ----------------------------------------------------------

log_file <- file.path(out_base, "PCA_Xtar_reduced_ingroup_MAF05_all_loci_log.txt")
if (file.exists(log_file)) file.remove(log_file)

log_msg <- function(...) {
  ts <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  line <- paste0(ts, " - ", paste(..., collapse = ""))
  cat(line, "\n", file = log_file, append = TRUE)
  message(paste(..., collapse = ""))
}

log_msg("=== Starting revised PCA pipeline ===")

## ----------------------------------------------------------
## 2. Species colors and shapes
## ----------------------------------------------------------

species_full_levels <- c(
  "P.perforatum", "P.hypotropum", "P.subrigidum",
  "P.louisianae", "P.preperforatum", "P.hypoleucinum"
)

colors <- c(
  "P.perforatum" = "#006400",
  "P.hypotropum" = "#90EE90",
  "P.subrigidum" = "#8B0000",
  "P.louisianae" = "#F08080",
  "P.preperforatum" = "#4B0082",
  "P.hypoleucinum" = "#D8BFD8"
)

shapes <- c(
  "P.perforatum" = 15,
  "P.hypotropum" = 16,
  "P.subrigidum" = 15,
  "P.louisianae" = 16,
  "P.preperforatum" = 15,
  "P.hypoleucinum" = 16
)

## ----------------------------------------------------------
## 3. Metadata helpers
## ----------------------------------------------------------

as_logical_outgroup <- function(x) {
  if (is.logical(x)) return(x)
  tolower(trimws(as.character(x))) %in% c("true", "t", "1", "yes", "y")
}

standardize_species <- function(x) {
  x <- tolower(trimws(as.character(x)))
  x <- gsub("^p\\.", "", x)
  x <- gsub("^p_", "", x)
  x
}

species_to_group <- function(x) paste0("P.", standardize_species(x))

## ----------------------------------------------------------
## 4. Load metadata
## ----------------------------------------------------------

if (!file.exists(meta_path)) stop("Metadata file not found: ", meta_path)
meta <- read.csv(meta_path, stringsAsFactors = FALSE)

required_cols <- c("sample", "species")
missing_required <- setdiff(required_cols, colnames(meta))
if (length(missing_required) > 0) {
  stop("Metadata is missing: ", paste(missing_required, collapse = ", "))
}

meta$sample <- trimws(as.character(meta$sample))
meta$species <- standardize_species(meta$species)
meta$is_outgroup <- if ("is_outgroup" %in% names(meta)) {
  as_logical_outgroup(meta$is_outgroup)
} else {
  FALSE
}
meta$is_outgroup <- meta$is_outgroup | meta$sample %in% outgroup_samples
meta_focal <- subset(meta, species %in% focal_species & !is_outgroup)

log_msg("Metadata rows total: ", nrow(meta))
log_msg("Focal ingroup metadata rows: ", nrow(meta_focal))

## ----------------------------------------------------------
## 5. Plot helper
## ----------------------------------------------------------

save_pc_pair <- function(df, asm, out_dir, x_pc, y_pc, percent_var) {
  x_num <- as.integer(sub("PC", "", x_pc))
  y_num <- as.integer(sub("PC", "", y_pc))
  x_lab <- paste0(x_pc, " (", round(percent_var[x_num], 1), "%)")
  y_lab <- paste0(y_pc, " (", round(percent_var[y_num], 1), "%)")
  pair_tag <- paste0(x_pc, "_", y_pc)

  base_aes <- aes(
    x = .data[[x_pc]], y = .data[[y_pc]],
    color = group, shape = group
  )

  p_points <- ggplot(df, base_aes) +
    geom_point(size = 3) +
    scale_color_manual(values = colors, breaks = species_full_levels, drop = FALSE) +
    scale_shape_manual(values = shapes, breaks = species_full_levels, drop = FALSE) +
    theme_minimal() +
    labs(x = x_lab, y = y_lab, color = "Species", shape = "Species",
         title = paste("PCA -", asm)) +
    theme(legend.position = "right", plot.title = element_text(hjust = 0.5))

  ggsave(file.path(out_dir, paste0("PCA_", asm, "_", pair_tag, "_points.png")),
         p_points, width = 6, height = 5, dpi = 300)
  ggsave(file.path(out_dir, paste0("PCA_", asm, "_", pair_tag, "_points.pdf")),
         p_points, width = 6, height = 5)

  ellipse_df <- df %>%
    group_by(group) %>%
    filter(n() >= 3,
           sd(.data[[x_pc]], na.rm = TRUE) > 0,
           sd(.data[[y_pc]], na.rm = TRUE) > 0) %>%
    ungroup()

  p_ellipses <- p_points
  if (nrow(ellipse_df) > 0) {
    p_ellipses <- p_points +
      stat_ellipse(
        data = ellipse_df,
        aes(x = .data[[x_pc]], y = .data[[y_pc]], color = group, group = group),
        inherit.aes = FALSE,
        level = 0.95,
        linewidth = 0.6,
        alpha = 0.4
      )
  }

  ggsave(file.path(out_dir, paste0("PCA_", asm, "_", pair_tag, "_ellipses.png")),
         p_ellipses, width = 6, height = 5, dpi = 300)
  ggsave(file.path(out_dir, paste0("PCA_", asm, "_", pair_tag, "_ellipses.pdf")),
         p_ellipses, width = 6, height = 5)

  invisible(list(points = p_points, ellipses = p_ellipses))
}

## ----------------------------------------------------------
## 6. Core PCA function
## ----------------------------------------------------------

run_pca <- function(asm, vcf_path, meta) {
  log_msg("\n----- ", asm, " -----")
  log_msg("Using VCF: ", vcf_path)

  if (!file.exists(vcf_path)) {
    stop("VCF not found: ", vcf_path, "\nRun filter_Xtar_ingroup_MAF05.R first.")
  }

  out_dir <- file.path(out_base, asm)
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

  vcf <- read.vcfR(vcf_path, verbose = FALSE)
  n_records <- nrow(vcf@fix)
  sample_names <- colnames(vcf@gt)[-1]

  log_msg("Variant records in VCF: ", n_records)
  log_msg("Individuals in VCF: ", length(sample_names))

  remaining_outgroups <- intersect(sample_names, outgroup_samples)
  if (length(remaining_outgroups) > 0) {
    stop("Outgroups remain in ", asm, ": ", paste(remaining_outgroups, collapse = ", "))
  }
  if (length(sample_names) != 104) {
    stop("Expected 104 ingroup samples in ", asm, ", found ", length(sample_names))
  }

  gen <- vcfR2genlight(vcf)
  ploidy(gen) <- rep(1L, nInd(gen))
  indNames(gen) <- trimws(indNames(gen))

  log_msg("Individuals in genlight: ", nInd(gen))
  log_msg("Loci in genlight before cleaning: ", nLoc(gen))

  missing_metadata <- setdiff(indNames(gen), meta$sample)
  if (length(missing_metadata) > 0) {
    stop("Samples missing from metadata: ", paste(missing_metadata, collapse = ", "))
  }

  gen_use <- gen[indNames(gen) %in% meta$sample]
  meta_use <- meta[match(indNames(gen_use), meta$sample), , drop = FALSE]

  if (!all(indNames(gen_use) == meta_use$sample)) {
    stop("Sample order mismatch for ", asm)
  }
  if (nInd(gen_use) != 104) {
    stop("Expected 104 matched ingroup samples in ", asm, ", found ", nInd(gen_use))
  }

  log_msg("Species counts: ",
          paste(capture.output(print(table(species_to_group(meta_use$species)))),
                collapse = " | "))

  log_msg("Building numeric matrix with mean imputation...")
  pca_time <- system.time({
    X <- tab(gen_use, NA.method = "mean", freq = FALSE)
    log_msg("Initial matrix: ", paste(dim(X), collapse = " x "), " (individuals x loci)")

    finite_ok <- apply(X, 2, function(z) all(is.finite(z)))
    var_ok <- apply(X, 2, function(z) all(is.finite(z)) && var(z) > 0)
    keep_cols <- finite_ok & var_ok

    log_msg("Dropping ", sum(!finite_ok), " non-finite loci and ",
            sum(finite_ok & !var_ok), " zero-variance loci")

    X <- X[, keep_cols, drop = FALSE]
    log_msg("Cleaned matrix: ", paste(dim(X), collapse = " x "), " (individuals x loci)")

    pca_obj <- prcomp(X, center = TRUE, scale. = FALSE)
  })

  log_msg("PCA finished in ", round(pca_time[["elapsed"]], 1), " sec")

  eigenvalues <- pca_obj$sdev^2
  percent_var <- eigenvalues / sum(eigenvalues) * 100
  log_msg("Variance explained: ",
          paste(paste0("PC", 1:4, " = ", round(percent_var[1:4], 2), "%"),
                collapse = ", "))

  scores <- as.data.frame(pca_obj$x[, 1:5, drop = FALSE])
  scores$sample <- indNames(gen_use)
  scores$species <- meta_use$species
  scores$group <- factor(species_to_group(scores$species), levels = species_full_levels)

  plots <- list()
  for (pair in pc_pairs) {
    log_msg("Saving ", pair[1], " versus ", pair[2])
    plots[[paste(pair, collapse = "_")]] <- save_pc_pair(
      scores, asm, out_dir, pair[1], pair[2], percent_var
    )
  }

  scree_n <- min(10, length(percent_var))
  scree_df <- data.frame(
    PC = factor(paste0("PC", 1:scree_n), levels = paste0("PC", 1:scree_n)),
    percent_variance = percent_var[1:scree_n]
  )
  p_scree <- ggplot(scree_df, aes(PC, percent_variance)) +
    geom_col() +
    theme_minimal() +
    labs(x = NULL, y = "Variance explained (%)",
         title = paste("PCA variance explained -", asm)) +
    theme(plot.title = element_text(hjust = 0.5))

  ggsave(file.path(out_dir, paste0("PCA_", asm, "_scree_PC1_PC10.png")),
         p_scree, width = 7, height = 4, dpi = 300)
  ggsave(file.path(out_dir, paste0("PCA_", asm, "_scree_PC1_PC10.pdf")),
         p_scree, width = 7, height = 4)

  write.table(scores,
              file.path(out_dir, paste0("PCA_", asm, "_scores.tsv")),
              sep = "\t", quote = FALSE, row.names = FALSE)

  eigen_out <- data.frame(
    PC = seq_along(eigenvalues),
    eigenvalue = eigenvalues,
    percent_variance = percent_var
  )
  write.table(eigen_out,
              file.path(out_dir, paste0("PCA_", asm, "_eigenvalues.tsv")),
              sep = "\t", quote = FALSE, row.names = FALSE)

  saveRDS(
    list(
      asm = asm,
      pca = pca_obj,
      scores = scores,
      eigenvalues = eigenvalues,
      percent_var = percent_var,
      n_variant_records = n_records,
      n_loci_before_cleaning = nLoc(gen_use),
      n_loci_after_cleaning = ncol(X),
      meta = meta_use,
      plots = plots,
      scree_plot = p_scree
    ),
    file.path(out_dir, paste0("PCA_", asm, "_objects.rds"))
  )

  invisible(list(
    asm = asm,
    pca = pca_obj,
    scores = scores,
    percent_var = percent_var,
    n_variant_records = n_records,
    n_loci_before_cleaning = nLoc(gen_use),
    n_loci_after_cleaning = ncol(X)
  ))
}

## ----------------------------------------------------------
## 7. Run all three datasets
## ----------------------------------------------------------

results <- list()
for (asm in names(vcf_paths)) {
  results[[asm]] <- run_pca(asm, vcf_paths[[asm]], meta_focal)
}

saveRDS(results,
        file.path(out_base, "PCA_Xtar_reduced_ingroup_MAF05_all_results.rds"))
log_msg("=== Finished revised PCA pipeline ===")
